### ISSUE TITLE
Unable to use import statements in step files

### ISSUE THREAD

**Issue by jmullo** [kiwigrid/gherkin-testcafe#21]
`gherkin-tescafe` could run those internally through Babel?

**Comment by Lukas-Kullmann** [comment]
Could you provide more context?

Do you mean using ES6 module import statements like 

```js
import { Selector } from 'testcafe';
```

No, this is not possible at the moment since the test files are run on your node process without transpilation.
You can however use `require` to import from modules:

```js
const { Selector } = require('testcafe');
```

Please note that it also relates to #12 where @DennisJaamann [suggested](https://github.com/kiwigrid/gherkin-testcafe/issues/12#issuecomment-439181635) to compile TS files before running the tests. You could do a similar thing with babel.

**Comment by jmullo** [comment]
Yes. I know. It would just be much more convenient if it was handled internally, just like TestCafe does.
