### ISSUE TITLE
Error in compliler.js when try run tests

### ISSUE THREAD

**Issue by maximkoev** [kiwigrid/gherkin-testcafe#44]
Hi guys, please help me, unfortunately I can't run tests since today morning (yesterday all worked good)

test run command:

```
    "testdev": "gherkin-testcafe chrome --tags @only"

```

here is my testcafe config
```
{
  "browsers": ["chromium:headless", "Firefox:headless"],
  "src": "./src/tests/",
  "reporter": [
    {
      "name": "list"
    },
    {
      "name": "json",
      "output": "reports/report.json"
    }
  ],
  "appCommand": "tsc -p tsconfig.e2e.json",
  "assertionTimeout": 9000,
  "speed": 0.8,
  "concurrency": 1,
``` 

ERROR TypeError: Cannot read property 'feature' of null
    at Promise.all.specFiles.map (/home/maximkoev/sources/Capita/kp-nbs-mvp/packages/automation/node_modules/gherkin-testcafe/src/compiler.js:70:62)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by Lukas-Kullmann** [comment]
Hi @maximkoev.,

could you please share the cucumber and gherkin version you have installed? (A quick way to find them is `npm ls gherkin cucumber`).

**Comment by maximkoev** [comment]
@Lukas-Kullmann 
Thank you for fast response, here are versions

├─┬ cucumber@5.1.0 
│ └── gherkin@5.1.0 
└─┬ gherkin-testcafe@2.3.3
  └── gherkin@6.0.17

**Comment by Lukas-Kullmann** [comment]
Thank you.

The problem is, that I cannot really reproduce your error on my side. I ran some tests with the versions you provided, but I do not see this error.

The only clue that I have at the moment is that there is a feature file in your tests that has a weird structure. Could you maybe find out if this error occurs if you run the tests for each feature file individually?
And if not, could you maybe provide a minimal example of a feature file that produces this error?

**Comment by maximkoev** [comment]
@Lukas-Kullmann  You are right Lukas it is problem on my side. Is one of the tests I missed colon after Scenario keyword :)

Thanks for you help

**Comment by Lukas-Kullmann** [comment]
Ok, thanks for the update.

In the next release, such errors will be handled and an error message will be shown.
